name: Run Twitter Bot

on:
    workflow_dispatch:
    schedule:
      - cron: '0 15 * * *'  # Schedule: Every day at 7pm
  
jobs:
    run-bot:
      runs-on: ubuntu-latest
  
      steps:
      - name: Check out code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run bot script
        env:
            CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

            DOG_API_KEY: ${{ secrets.DOG_API_KEY }}

            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_USER_PASS: ${{ secrets.DB_USER_PASS }}
            DB_NAME: ${{ secrets.DB_NAME }}
            CERT_PATH: './cert_tmp.pem'
        run: |
            echo "${{ secrets.CERTIFICAT_BASE64 }}" | base64 --decode > ./cert_tmp.pem
            python main.py